namespace TeacherManajar
{
    partial class FormEntry
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormEntry));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabelError = new Bunifu.UI.WinForms.BunifuLabel();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuGradientPanelTop = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.labelTitle = new System.Windows.Forms.Label();
            this.bunifuButtonMinimized = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuToolTip = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuButtonRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonForgotPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButtonEntry = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuCheckBox2 = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuTextBoxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGradientPanelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabelError
            // 
            this.bunifuLabelError.AllowParentOverrides = false;
            this.bunifuLabelError.AutoEllipsis = false;
            this.bunifuLabelError.AutoSize = false;
            this.bunifuLabelError.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabelError.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabelError.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuLabelError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.bunifuLabelError.Location = new System.Drawing.Point(64, 249);
            this.bunifuLabelError.Name = "bunifuLabelError";
            this.bunifuLabelError.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabelError.Size = new System.Drawing.Size(288, 18);
            this.bunifuLabelError.TabIndex = 14;
            this.bunifuLabelError.Text = "Будь ласка введіть дійсу адресу електронної пошти";
            this.bunifuLabelError.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabelError.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip.SetToolTip(this.bunifuLabelError, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuLabelError, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuLabelError, "");
            this.bunifuLabelError.Visible = false;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.label1.Font = new System.Drawing.Font("Times New Roman", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label1.Location = new System.Drawing.Point(270, 350);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(149, 25);
            this.label1.TabIndex = 23;
            this.label1.Text = "Зберегти Email";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuToolTip.SetToolTip(this.label1, "");
            this.bunifuToolTip.SetToolTipIcon(this.label1, null);
            this.bunifuToolTip.SetToolTipTitle(this.label1, "");
            // 
            // bunifuFormDock
            // 
            this.bunifuFormDock.AllowFormDragging = false;
            this.bunifuFormDock.AllowFormDropShadow = true;
            this.bunifuFormDock.AllowFormResizing = false;
            this.bunifuFormDock.AllowHidingBottomRegion = true;
            this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock.ContainerControl = this;
            this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock.DockingOptions.DockAll = true;
            this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock.DockingOptions.DockLeft = true;
            this.bunifuFormDock.DockingOptions.DockRight = true;
            this.bunifuFormDock.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock.DockingOptions.DockTopRight = true;
            this.bunifuFormDock.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock.ParentForm = this;
            this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = true;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = this.bunifuGradientPanelTop;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuGradientPanelTop
            // 
            this.bunifuGradientPanelTop.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanelTop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanelTop.BackgroundImage")));
            this.bunifuGradientPanelTop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanelTop.BorderRadius = 1;
            this.bunifuGradientPanelTop.Controls.Add(this.labelTitle);
            this.bunifuGradientPanelTop.Controls.Add(this.bunifuButtonMinimized);
            this.bunifuGradientPanelTop.Controls.Add(this.bunifuButtonClose);
            this.bunifuGradientPanelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanelTop.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(136)))), ((int)(((byte)(146)))));
            this.bunifuGradientPanelTop.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(86)))), ((int)(((byte)(102)))));
            this.bunifuGradientPanelTop.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(212)))), ((int)(((byte)(213)))));
            this.bunifuGradientPanelTop.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(149)))), ((int)(((byte)(158)))));
            this.bunifuGradientPanelTop.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanelTop.Name = "bunifuGradientPanelTop";
            this.bunifuGradientPanelTop.Quality = 10;
            this.bunifuGradientPanelTop.Size = new System.Drawing.Size(635, 93);
            this.bunifuGradientPanelTop.TabIndex = 28;
            this.bunifuToolTip.SetToolTip(this.bunifuGradientPanelTop, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuGradientPanelTop, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuGradientPanelTop, "");
            // 
            // labelTitle
            // 
            this.labelTitle.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.labelTitle.Font = new System.Drawing.Font("Times New Roman", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelTitle.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.labelTitle.Location = new System.Drawing.Point(110, 24);
            this.labelTitle.Name = "labelTitle";
            this.labelTitle.Size = new System.Drawing.Size(415, 45);
            this.labelTitle.TabIndex = 31;
            this.labelTitle.Text = "Вхід в особистий кабінет";
            this.bunifuToolTip.SetToolTip(this.labelTitle, "");
            this.bunifuToolTip.SetToolTipIcon(this.labelTitle, null);
            this.bunifuToolTip.SetToolTipTitle(this.labelTitle, "");
            // 
            // bunifuButtonMinimized
            // 
            this.bunifuButtonMinimized.AllowAnimations = true;
            this.bunifuButtonMinimized.AllowMouseEffects = true;
            this.bunifuButtonMinimized.AllowToggling = false;
            this.bunifuButtonMinimized.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonMinimized.AnimationSpeed = 200;
            this.bunifuButtonMinimized.AutoGenerateColors = false;
            this.bunifuButtonMinimized.AutoRoundBorders = false;
            this.bunifuButtonMinimized.AutoSizeLeftIcon = true;
            this.bunifuButtonMinimized.AutoSizeRightIcon = true;
            this.bunifuButtonMinimized.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButtonMinimized.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMinimized.BackgroundImage")));
            this.bunifuButtonMinimized.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.ButtonText = "";
            this.bunifuButtonMinimized.ButtonTextMarginLeft = 0;
            this.bunifuButtonMinimized.ColorContrastOnClick = 45;
            this.bunifuButtonMinimized.ColorContrastOnHover = 45;
            this.bunifuButtonMinimized.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.bunifuButtonMinimized.CustomizableEdges = borderEdges11;
            this.bunifuButtonMinimized.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMinimized.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMinimized.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMinimized.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonMinimized.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.IconLeft = null;
            this.bunifuButtonMinimized.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMinimized.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMinimized.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMinimized.IconMarginLeft = 11;
            this.bunifuButtonMinimized.IconPadding = 10;
            this.bunifuButtonMinimized.IconRight = global::TeacherManajar.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMinimized.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonMinimized.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMinimized.IconSize = 26;
            this.bunifuButtonMinimized.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.IdleBorderRadius = 0;
            this.bunifuButtonMinimized.IdleBorderThickness = 0;
            this.bunifuButtonMinimized.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonMinimized.IdleIconLeftImage = null;
            this.bunifuButtonMinimized.IdleIconRightImage = global::TeacherManajar.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.IndicateFocus = true;
            this.bunifuButtonMinimized.Location = new System.Drawing.Point(568, 0);
            this.bunifuButtonMinimized.Name = "bunifuButtonMinimized";
            this.bunifuButtonMinimized.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMinimized.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMinimized.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMinimized.onHoverState.BorderColor = System.Drawing.Color.Blue;
            this.bunifuButtonMinimized.onHoverState.BorderRadius = 1;
            this.bunifuButtonMinimized.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.onHoverState.BorderThickness = 1;
            this.bunifuButtonMinimized.onHoverState.FillColor = System.Drawing.Color.Blue;
            this.bunifuButtonMinimized.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.onHoverState.IconLeftImage = null;
            this.bunifuButtonMinimized.onHoverState.IconRightImage = null;
            this.bunifuButtonMinimized.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.OnIdleState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMinimized.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnIdleState.IconRightImage = global::TeacherManajar.Properties.Resources.minimise_32px;
            this.bunifuButtonMinimized.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnPressedState.BorderRadius = 1;
            this.bunifuButtonMinimized.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMinimized.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMinimized.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(102)))), ((int)(((byte)(204)))));
            this.bunifuButtonMinimized.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMinimized.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMinimized.OnPressedState.IconRightImage = null;
            this.bunifuButtonMinimized.Size = new System.Drawing.Size(33, 40);
            this.bunifuButtonMinimized.TabIndex = 30;
            this.bunifuButtonMinimized.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMinimized.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMinimized.TextMarginLeft = 0;
            this.bunifuButtonMinimized.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonMinimized, "Вийти");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonMinimized, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonMinimized, "");
            this.bunifuButtonMinimized.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonClose
            // 
            this.bunifuButtonClose.AllowAnimations = true;
            this.bunifuButtonClose.AllowMouseEffects = true;
            this.bunifuButtonClose.AllowToggling = false;
            this.bunifuButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButtonClose.AnimationSpeed = 200;
            this.bunifuButtonClose.AutoGenerateColors = false;
            this.bunifuButtonClose.AutoRoundBorders = false;
            this.bunifuButtonClose.AutoSizeLeftIcon = true;
            this.bunifuButtonClose.AutoSizeRightIcon = true;
            this.bunifuButtonClose.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButtonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonClose.BackgroundImage")));
            this.bunifuButtonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.ButtonText = "";
            this.bunifuButtonClose.ButtonTextMarginLeft = 0;
            this.bunifuButtonClose.ColorContrastOnClick = 45;
            this.bunifuButtonClose.ColorContrastOnHover = 45;
            this.bunifuButtonClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.bunifuButtonClose.CustomizableEdges = borderEdges12;
            this.bunifuButtonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonClose.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.IconLeft = null;
            this.bunifuButtonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonClose.IconMarginLeft = 11;
            this.bunifuButtonClose.IconPadding = 10;
            this.bunifuButtonClose.IconRight = global::TeacherManajar.Properties.Resources.Close_32px;
            this.bunifuButtonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonClose.IconSize = 26;
            this.bunifuButtonClose.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.IdleBorderRadius = 0;
            this.bunifuButtonClose.IdleBorderThickness = 0;
            this.bunifuButtonClose.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButtonClose.IdleIconLeftImage = null;
            this.bunifuButtonClose.IdleIconRightImage = global::TeacherManajar.Properties.Resources.Close_32px;
            this.bunifuButtonClose.IndicateFocus = true;
            this.bunifuButtonClose.Location = new System.Drawing.Point(602, 0);
            this.bunifuButtonClose.Name = "bunifuButtonClose";
            this.bunifuButtonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonClose.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonClose.OnDisabledState.IconRightImage = null;
            this.bunifuButtonClose.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButtonClose.onHoverState.BorderRadius = 1;
            this.bunifuButtonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.onHoverState.BorderThickness = 1;
            this.bunifuButtonClose.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButtonClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.onHoverState.IconLeftImage = null;
            this.bunifuButtonClose.onHoverState.IconRightImage = null;
            this.bunifuButtonClose.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.OnIdleState.BorderRadius = 1;
            this.bunifuButtonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnIdleState.BorderThickness = 1;
            this.bunifuButtonClose.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.OnIdleState.IconLeftImage = null;
            this.bunifuButtonClose.OnIdleState.IconRightImage = global::TeacherManajar.Properties.Resources.Close_32px;
            this.bunifuButtonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(0)))), ((int)(((byte)(51)))));
            this.bunifuButtonClose.OnPressedState.BorderRadius = 1;
            this.bunifuButtonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnPressedState.BorderThickness = 1;
            this.bunifuButtonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(0)))), ((int)(((byte)(51)))));
            this.bunifuButtonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.OnPressedState.IconLeftImage = null;
            this.bunifuButtonClose.OnPressedState.IconRightImage = null;
            this.bunifuButtonClose.Size = new System.Drawing.Size(33, 40);
            this.bunifuButtonClose.TabIndex = 29;
            this.bunifuButtonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonClose.TextMarginLeft = 0;
            this.bunifuButtonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonClose, "Вийти");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonClose, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonClose, "");
            this.bunifuButtonClose.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuToolTip
            // 
            this.bunifuToolTip.Active = true;
            this.bunifuToolTip.AlignTextWithTitle = false;
            this.bunifuToolTip.AllowAutoClose = false;
            this.bunifuToolTip.AllowFading = true;
            this.bunifuToolTip.AutoCloseDuration = 5000;
            this.bunifuToolTip.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip.ClickToShowDisplayControl = false;
            this.bunifuToolTip.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip.DisplayControl = null;
            this.bunifuToolTip.EntryAnimationSpeed = 350;
            this.bunifuToolTip.ExitAnimationSpeed = 200;
            this.bunifuToolTip.GenerateAutoCloseDuration = false;
            this.bunifuToolTip.IconMargin = 6;
            this.bunifuToolTip.InitialDelay = 0;
            this.bunifuToolTip.Name = "bunifuToolTip";
            this.bunifuToolTip.Opacity = 1D;
            this.bunifuToolTip.OverrideToolTipTitles = false;
            this.bunifuToolTip.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip.ReshowDelay = 100;
            this.bunifuToolTip.ShowAlways = true;
            this.bunifuToolTip.ShowBorders = false;
            this.bunifuToolTip.ShowIcons = true;
            this.bunifuToolTip.ShowShadows = true;
            this.bunifuToolTip.Tag = null;
            this.bunifuToolTip.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip.TextMargin = 2;
            this.bunifuToolTip.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip.ToolTipTitle = null;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 50;
            this.bunifuPictureBox1.Image = global::TeacherManajar.Properties.Resources.enter_100px;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(268, 99);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(100, 100);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 29;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuButtonRegister
            // 
            this.bunifuButtonRegister.AllowAnimations = true;
            this.bunifuButtonRegister.AllowMouseEffects = true;
            this.bunifuButtonRegister.AllowToggling = false;
            this.bunifuButtonRegister.AnimationSpeed = 200;
            this.bunifuButtonRegister.AutoGenerateColors = false;
            this.bunifuButtonRegister.AutoRoundBorders = false;
            this.bunifuButtonRegister.AutoSizeLeftIcon = true;
            this.bunifuButtonRegister.AutoSizeRightIcon = true;
            this.bunifuButtonRegister.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRegister.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonRegister.BackgroundImage")));
            this.bunifuButtonRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonRegister.ButtonText = "Реєстрація";
            this.bunifuButtonRegister.ButtonTextMarginLeft = 0;
            this.bunifuButtonRegister.ColorContrastOnClick = 45;
            this.bunifuButtonRegister.ColorContrastOnHover = 45;
            this.bunifuButtonRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.bunifuButtonRegister.CustomizableEdges = borderEdges13;
            this.bunifuButtonRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRegister.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonRegister.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButtonRegister.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonRegister.IconMarginLeft = 11;
            this.bunifuButtonRegister.IconPadding = 10;
            this.bunifuButtonRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRegister.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonRegister.IconSize = 25;
            this.bunifuButtonRegister.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonRegister.IdleBorderRadius = 20;
            this.bunifuButtonRegister.IdleBorderThickness = 1;
            this.bunifuButtonRegister.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonRegister.IdleIconLeftImage = global::TeacherManajar.Properties.Resources.registration_32px;
            this.bunifuButtonRegister.IdleIconRightImage = null;
            this.bunifuButtonRegister.IndicateFocus = false;
            this.bunifuButtonRegister.Location = new System.Drawing.Point(64, 506);
            this.bunifuButtonRegister.Name = "bunifuButtonRegister";
            this.bunifuButtonRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRegister.OnDisabledState.BorderRadius = 20;
            this.bunifuButtonRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonRegister.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRegister.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonRegister.OnDisabledState.IconRightImage = null;
            this.bunifuButtonRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRegister.onHoverState.BorderRadius = 20;
            this.bunifuButtonRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonRegister.onHoverState.BorderThickness = 1;
            this.bunifuButtonRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRegister.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegister.onHoverState.IconLeftImage = null;
            this.bunifuButtonRegister.onHoverState.IconRightImage = null;
            this.bunifuButtonRegister.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonRegister.OnIdleState.BorderRadius = 20;
            this.bunifuButtonRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonRegister.OnIdleState.BorderThickness = 1;
            this.bunifuButtonRegister.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonRegister.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegister.OnIdleState.IconLeftImage = global::TeacherManajar.Properties.Resources.registration_32px;
            this.bunifuButtonRegister.OnIdleState.IconRightImage = null;
            this.bunifuButtonRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRegister.OnPressedState.BorderRadius = 20;
            this.bunifuButtonRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonRegister.OnPressedState.BorderThickness = 1;
            this.bunifuButtonRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRegister.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegister.OnPressedState.IconLeftImage = null;
            this.bunifuButtonRegister.OnPressedState.IconRightImage = null;
            this.bunifuButtonRegister.Size = new System.Drawing.Size(160, 40);
            this.bunifuButtonRegister.TabIndex = 23;
            this.bunifuButtonRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonRegister.TextMarginLeft = 0;
            this.bunifuButtonRegister.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonRegister, "Зареєструвати новий акаунт");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonRegister, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonRegister, "");
            this.bunifuButtonRegister.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonRegister.Click += new System.EventHandler(this.Register_Click);
            // 
            // bunifuButtonForgotPassword
            // 
            this.bunifuButtonForgotPassword.AllowAnimations = true;
            this.bunifuButtonForgotPassword.AllowMouseEffects = true;
            this.bunifuButtonForgotPassword.AllowToggling = false;
            this.bunifuButtonForgotPassword.AnimationSpeed = 200;
            this.bunifuButtonForgotPassword.AutoGenerateColors = false;
            this.bunifuButtonForgotPassword.AutoRoundBorders = false;
            this.bunifuButtonForgotPassword.AutoSizeLeftIcon = true;
            this.bunifuButtonForgotPassword.AutoSizeRightIcon = true;
            this.bunifuButtonForgotPassword.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonForgotPassword.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonForgotPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonForgotPassword.BackgroundImage")));
            this.bunifuButtonForgotPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonForgotPassword.ButtonText = "Забули пароль";
            this.bunifuButtonForgotPassword.ButtonTextMarginLeft = 0;
            this.bunifuButtonForgotPassword.ColorContrastOnClick = 45;
            this.bunifuButtonForgotPassword.ColorContrastOnHover = 45;
            this.bunifuButtonForgotPassword.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.bunifuButtonForgotPassword.CustomizableEdges = borderEdges14;
            this.bunifuButtonForgotPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonForgotPassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonForgotPassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonForgotPassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonForgotPassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonForgotPassword.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButtonForgotPassword.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonForgotPassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonForgotPassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonForgotPassword.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 3, 3);
            this.bunifuButtonForgotPassword.IconMarginLeft = 11;
            this.bunifuButtonForgotPassword.IconPadding = 10;
            this.bunifuButtonForgotPassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonForgotPassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonForgotPassword.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonForgotPassword.IconSize = 25;
            this.bunifuButtonForgotPassword.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonForgotPassword.IdleBorderRadius = 20;
            this.bunifuButtonForgotPassword.IdleBorderThickness = 1;
            this.bunifuButtonForgotPassword.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonForgotPassword.IdleIconLeftImage = global::TeacherManajar.Properties.Resources.forgot_password_32px;
            this.bunifuButtonForgotPassword.IdleIconRightImage = null;
            this.bunifuButtonForgotPassword.IndicateFocus = false;
            this.bunifuButtonForgotPassword.Location = new System.Drawing.Point(397, 506);
            this.bunifuButtonForgotPassword.Name = "bunifuButtonForgotPassword";
            this.bunifuButtonForgotPassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonForgotPassword.OnDisabledState.BorderRadius = 20;
            this.bunifuButtonForgotPassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonForgotPassword.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonForgotPassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonForgotPassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonForgotPassword.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonForgotPassword.OnDisabledState.IconRightImage = null;
            this.bunifuButtonForgotPassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonForgotPassword.onHoverState.BorderRadius = 20;
            this.bunifuButtonForgotPassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonForgotPassword.onHoverState.BorderThickness = 1;
            this.bunifuButtonForgotPassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonForgotPassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonForgotPassword.onHoverState.IconLeftImage = null;
            this.bunifuButtonForgotPassword.onHoverState.IconRightImage = null;
            this.bunifuButtonForgotPassword.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonForgotPassword.OnIdleState.BorderRadius = 20;
            this.bunifuButtonForgotPassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonForgotPassword.OnIdleState.BorderThickness = 1;
            this.bunifuButtonForgotPassword.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonForgotPassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonForgotPassword.OnIdleState.IconLeftImage = global::TeacherManajar.Properties.Resources.forgot_password_32px;
            this.bunifuButtonForgotPassword.OnIdleState.IconRightImage = null;
            this.bunifuButtonForgotPassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonForgotPassword.OnPressedState.BorderRadius = 20;
            this.bunifuButtonForgotPassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonForgotPassword.OnPressedState.BorderThickness = 1;
            this.bunifuButtonForgotPassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonForgotPassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonForgotPassword.OnPressedState.IconLeftImage = null;
            this.bunifuButtonForgotPassword.OnPressedState.IconRightImage = null;
            this.bunifuButtonForgotPassword.Size = new System.Drawing.Size(185, 40);
            this.bunifuButtonForgotPassword.TabIndex = 24;
            this.bunifuButtonForgotPassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonForgotPassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonForgotPassword.TextMarginLeft = 0;
            this.bunifuButtonForgotPassword.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonForgotPassword, "Відновити пароль до особистого кабінету");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonForgotPassword, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonForgotPassword, "");
            this.bunifuButtonForgotPassword.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButtonEntry
            // 
            this.bunifuButtonEntry.AllowAnimations = true;
            this.bunifuButtonEntry.AllowMouseEffects = true;
            this.bunifuButtonEntry.AllowToggling = false;
            this.bunifuButtonEntry.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuButtonEntry.AnimationSpeed = 200;
            this.bunifuButtonEntry.AutoGenerateColors = false;
            this.bunifuButtonEntry.AutoRoundBorders = false;
            this.bunifuButtonEntry.AutoSizeLeftIcon = true;
            this.bunifuButtonEntry.AutoSizeRightIcon = true;
            this.bunifuButtonEntry.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonEntry.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonEntry.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonEntry.BackgroundImage")));
            this.bunifuButtonEntry.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonEntry.ButtonText = "Увійти";
            this.bunifuButtonEntry.ButtonTextMarginLeft = 0;
            this.bunifuButtonEntry.ColorContrastOnClick = 45;
            this.bunifuButtonEntry.ColorContrastOnHover = 45;
            this.bunifuButtonEntry.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.bunifuButtonEntry.CustomizableEdges = borderEdges15;
            this.bunifuButtonEntry.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonEntry.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonEntry.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonEntry.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonEntry.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButtonEntry.Font = new System.Drawing.Font("Georgia", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuButtonEntry.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonEntry.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonEntry.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonEntry.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonEntry.IconMarginLeft = 11;
            this.bunifuButtonEntry.IconPadding = 10;
            this.bunifuButtonEntry.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonEntry.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonEntry.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonEntry.IconSize = 25;
            this.bunifuButtonEntry.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonEntry.IdleBorderRadius = 40;
            this.bunifuButtonEntry.IdleBorderThickness = 1;
            this.bunifuButtonEntry.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonEntry.IdleIconLeftImage = null;
            this.bunifuButtonEntry.IdleIconRightImage = null;
            this.bunifuButtonEntry.IndicateFocus = false;
            this.bunifuButtonEntry.Location = new System.Drawing.Point(200, 405);
            this.bunifuButtonEntry.Name = "bunifuButtonEntry";
            this.bunifuButtonEntry.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonEntry.OnDisabledState.BorderRadius = 40;
            this.bunifuButtonEntry.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonEntry.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonEntry.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonEntry.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonEntry.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonEntry.OnDisabledState.IconRightImage = null;
            this.bunifuButtonEntry.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonEntry.onHoverState.BorderRadius = 40;
            this.bunifuButtonEntry.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonEntry.onHoverState.BorderThickness = 1;
            this.bunifuButtonEntry.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonEntry.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonEntry.onHoverState.IconLeftImage = null;
            this.bunifuButtonEntry.onHoverState.IconRightImage = null;
            this.bunifuButtonEntry.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonEntry.OnIdleState.BorderRadius = 40;
            this.bunifuButtonEntry.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonEntry.OnIdleState.BorderThickness = 1;
            this.bunifuButtonEntry.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonEntry.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonEntry.OnIdleState.IconLeftImage = null;
            this.bunifuButtonEntry.OnIdleState.IconRightImage = null;
            this.bunifuButtonEntry.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonEntry.OnPressedState.BorderRadius = 40;
            this.bunifuButtonEntry.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButtonEntry.OnPressedState.BorderThickness = 1;
            this.bunifuButtonEntry.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonEntry.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonEntry.OnPressedState.IconLeftImage = null;
            this.bunifuButtonEntry.OnPressedState.IconRightImage = null;
            this.bunifuButtonEntry.Size = new System.Drawing.Size(255, 56);
            this.bunifuButtonEntry.TabIndex = 26;
            this.bunifuButtonEntry.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonEntry.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonEntry.TextMarginLeft = 0;
            this.bunifuButtonEntry.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip.SetToolTip(this.bunifuButtonEntry, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuButtonEntry, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuButtonEntry, "");
            this.bunifuButtonEntry.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonEntry.Click += new System.EventHandler(this.Entry_Click);
            // 
            // bunifuCheckBox2
            // 
            this.bunifuCheckBox2.AllowBindingControlAnimation = true;
            this.bunifuCheckBox2.AllowBindingControlColorChanges = false;
            this.bunifuCheckBox2.AllowBindingControlLocation = true;
            this.bunifuCheckBox2.AllowCheckBoxAnimation = false;
            this.bunifuCheckBox2.AllowCheckmarkAnimation = true;
            this.bunifuCheckBox2.AllowOnHoverStates = true;
            this.bunifuCheckBox2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuCheckBox2.AutoCheck = true;
            this.bunifuCheckBox2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuCheckBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuCheckBox2.BackgroundImage")));
            this.bunifuCheckBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuCheckBox2.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.bunifuCheckBox2.BorderRadius = 12;
            this.bunifuCheckBox2.Checked = false;
            this.bunifuCheckBox2.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.bunifuCheckBox2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuCheckBox2.CustomCheckmarkImage = null;
            this.bunifuCheckBox2.Location = new System.Drawing.Point(245, 350);
            this.bunifuCheckBox2.MinimumSize = new System.Drawing.Size(17, 17);
            this.bunifuCheckBox2.Name = "bunifuCheckBox2";
            this.bunifuCheckBox2.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuCheckBox2.OnCheck.BorderRadius = 12;
            this.bunifuCheckBox2.OnCheck.BorderThickness = 2;
            this.bunifuCheckBox2.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.bunifuCheckBox2.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.bunifuCheckBox2.OnCheck.CheckmarkThickness = 2;
            this.bunifuCheckBox2.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuCheckBox2.OnDisable.BorderRadius = 12;
            this.bunifuCheckBox2.OnDisable.BorderThickness = 2;
            this.bunifuCheckBox2.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.bunifuCheckBox2.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.bunifuCheckBox2.OnDisable.CheckmarkThickness = 2;
            this.bunifuCheckBox2.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuCheckBox2.OnHoverChecked.BorderRadius = 12;
            this.bunifuCheckBox2.OnHoverChecked.BorderThickness = 2;
            this.bunifuCheckBox2.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuCheckBox2.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.bunifuCheckBox2.OnHoverChecked.CheckmarkThickness = 2;
            this.bunifuCheckBox2.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuCheckBox2.OnHoverUnchecked.BorderRadius = 12;
            this.bunifuCheckBox2.OnHoverUnchecked.BorderThickness = 1;
            this.bunifuCheckBox2.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.bunifuCheckBox2.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.bunifuCheckBox2.OnUncheck.BorderRadius = 12;
            this.bunifuCheckBox2.OnUncheck.BorderThickness = 1;
            this.bunifuCheckBox2.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.bunifuCheckBox2.Size = new System.Drawing.Size(25, 25);
            this.bunifuCheckBox2.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.bunifuCheckBox2.TabIndex = 22;
            this.bunifuCheckBox2.ThreeState = false;
            this.bunifuToolTip.SetToolTip(this.bunifuCheckBox2, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuCheckBox2, null);
            this.bunifuCheckBox2.ToolTipText = null;
            this.bunifuToolTip.SetToolTipTitle(this.bunifuCheckBox2, "");
            // 
            // bunifuTextBoxEmail
            // 
            this.bunifuTextBoxEmail.AcceptsReturn = false;
            this.bunifuTextBoxEmail.AcceptsTab = false;
            this.bunifuTextBoxEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuTextBoxEmail.AnimationSpeed = 200;
            this.bunifuTextBoxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxEmail.AutoSizeHeight = true;
            this.bunifuTextBoxEmail.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxEmail.BackgroundImage")));
            this.bunifuTextBoxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxEmail.BorderRadius = 22;
            this.bunifuTextBoxEmail.BorderThickness = 1;
            this.bunifuTextBoxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.DefaultFont = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuTextBoxEmail.DefaultText = "";
            this.bunifuTextBoxEmail.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxEmail.HideSelection = true;
            this.bunifuTextBoxEmail.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxEmail.IconLeft")));
            this.bunifuTextBoxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.IconPadding = 5;
            this.bunifuTextBoxEmail.IconRight = null;
            this.bunifuTextBoxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.Lines = new string[0];
            this.bunifuTextBoxEmail.Location = new System.Drawing.Point(64, 199);
            this.bunifuTextBoxEmail.MaxLength = 255;
            this.bunifuTextBoxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxEmail.Modified = false;
            this.bunifuTextBoxEmail.Multiline = false;
            this.bunifuTextBoxEmail.Name = "bunifuTextBoxEmail";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxEmail.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnIdleState = stateProperties20;
            this.bunifuTextBoxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxEmail.PasswordChar = '\0';
            this.bunifuTextBoxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxEmail.PlaceholderText = "Введіть дані (...@gmail.com або ...@ukr.net)";
            this.bunifuTextBoxEmail.ReadOnly = false;
            this.bunifuTextBoxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxEmail.SelectedText = "";
            this.bunifuTextBoxEmail.SelectionLength = 0;
            this.bunifuTextBoxEmail.SelectionStart = 0;
            this.bunifuTextBoxEmail.ShortcutsEnabled = true;
            this.bunifuTextBoxEmail.Size = new System.Drawing.Size(518, 44);
            this.bunifuTextBoxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxEmail.TabIndex = 0;
            this.bunifuTextBoxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxEmail.TextMarginBottom = 0;
            this.bunifuTextBoxEmail.TextMarginLeft = 5;
            this.bunifuTextBoxEmail.TextMarginTop = 1;
            this.bunifuTextBoxEmail.TextPlaceholder = "Введіть дані (...@gmail.com або ...@ukr.net)";
            this.bunifuToolTip.SetToolTip(this.bunifuTextBoxEmail, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuTextBoxEmail, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuTextBoxEmail, "");
            this.bunifuTextBoxEmail.UseSystemPasswordChar = false;
            this.bunifuTextBoxEmail.WordWrap = true;
            this.bunifuTextBoxEmail.TextChanged += new System.EventHandler(this.Email_TextChanged);
            // 
            // bunifuTextBoxPassword
            // 
            this.bunifuTextBoxPassword.AcceptsReturn = false;
            this.bunifuTextBoxPassword.AcceptsTab = false;
            this.bunifuTextBoxPassword.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuTextBoxPassword.AnimationSpeed = 200;
            this.bunifuTextBoxPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPassword.AutoSizeHeight = true;
            this.bunifuTextBoxPassword.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPassword.BackgroundImage")));
            this.bunifuTextBoxPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPassword.BorderRadius = 22;
            this.bunifuTextBoxPassword.BorderThickness = 1;
            this.bunifuTextBoxPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.DefaultFont = new System.Drawing.Font("Times New Roman", 14.25F);
            this.bunifuTextBoxPassword.DefaultText = "";
            this.bunifuTextBoxPassword.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPassword.HideSelection = true;
            this.bunifuTextBoxPassword.IconLeft = global::TeacherManajar.Properties.Resources.password_45px;
            this.bunifuTextBoxPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.IconPadding = 5;
            this.bunifuTextBoxPassword.IconRight = global::TeacherManajar.Properties.Resources.closed_eye_45px;
            this.bunifuTextBoxPassword.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuTextBoxPassword.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bunifuTextBoxPassword.Lines = new string[0];
            this.bunifuTextBoxPassword.Location = new System.Drawing.Point(64, 281);
            this.bunifuTextBoxPassword.MaxLength = 255;
            this.bunifuTextBoxPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPassword.Modified = false;
            this.bunifuTextBoxPassword.Multiline = false;
            this.bunifuTextBoxPassword.Name = "bunifuTextBoxPassword";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPassword.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnIdleState = stateProperties24;
            this.bunifuTextBoxPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxPassword.PasswordChar = '\0';
            this.bunifuTextBoxPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxPassword.PlaceholderText = "Пароль";
            this.bunifuTextBoxPassword.ReadOnly = false;
            this.bunifuTextBoxPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPassword.SelectedText = "";
            this.bunifuTextBoxPassword.SelectionLength = 0;
            this.bunifuTextBoxPassword.SelectionStart = 0;
            this.bunifuTextBoxPassword.ShortcutsEnabled = true;
            this.bunifuTextBoxPassword.Size = new System.Drawing.Size(518, 44);
            this.bunifuTextBoxPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxPassword.TabIndex = 1;
            this.bunifuTextBoxPassword.Tag = "Пароль";
            this.bunifuTextBoxPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPassword.TextMarginBottom = 0;
            this.bunifuTextBoxPassword.TextMarginLeft = 5;
            this.bunifuTextBoxPassword.TextMarginTop = 1;
            this.bunifuTextBoxPassword.TextPlaceholder = "Пароль";
            this.bunifuToolTip.SetToolTip(this.bunifuTextBoxPassword, "");
            this.bunifuToolTip.SetToolTipIcon(this.bunifuTextBoxPassword, null);
            this.bunifuToolTip.SetToolTipTitle(this.bunifuTextBoxPassword, "");
            this.bunifuTextBoxPassword.UseSystemPasswordChar = false;
            this.bunifuTextBoxPassword.WordWrap = true;
            // 
            // FormEntry
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(635, 563);
            this.ControlBox = false;
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuButtonRegister);
            this.Controls.Add(this.bunifuButtonForgotPassword);
            this.Controls.Add(this.bunifuGradientPanelTop);
            this.Controls.Add(this.bunifuButtonEntry);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuCheckBox2);
            this.Controls.Add(this.bunifuLabelError);
            this.Controls.Add(this.bunifuTextBoxEmail);
            this.Controls.Add(this.bunifuTextBoxPassword);
            this.Font = new System.Drawing.Font("Times New Roman", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormEntry";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.bunifuGradientPanelTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPassword;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabelError;
        private Bunifu.UI.WinForms.BunifuCheckBox bunifuCheckBox2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonEntry;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanelTop;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonClose;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMinimized;
        private System.Windows.Forms.Label labelTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonRegister;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButtonForgotPassword;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}
